services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-network
    volumes:
      - mongo-db-data:/data/db/

volumes:
  mongo-db-data:
networks:
  mongo-network:
    name: mongo-network